Repository eclipse-ditto/ditto, pull requests merged in 2023-11, with the labels that each got.

#1782 fix that ThingFieldSelector did not allow specific paths of "_metadata"
  things/model/src/main/java/org/eclipse/ditto/things/model/ThingFieldSelector.java
  things/model/src/main/java/org/eclipse/ditto/things/model/ThingsModelFactory.java
Labels: bug

#1787 Move x-ditto-pre-authenticated and X-Forwarded-User to ingress.api.annotations
  .github/workflows/helm-chart.yml
  deployment/helm/ditto/Chart.yaml
  deployment/helm/ditto/templates/nginx-ingress.yaml
  deployment/helm/ditto/values.yaml
Labels: Helm chart

#1792 fix preserving DittoHeaders when encountering a JsonParseException
  base/api/src/main/java/org/eclipse/ditto/base/api/devops/signals/commands/DevOpsErrorResponse.java
  connectivity/model/src/main/java/org/eclipse/ditto/connectivity/model/signals/commands/ConnectivityErrorResponse.java
  connectivity/model/src/main/java/org/eclipse/ditto/connectivity/model/signals/commands/query/RetrieveConnectionsResponse.java
  connectivity/service/src/main/java/org/eclipse/ditto/connectivity/service/mapping/CloudEventsMapper.java
  connectivity/service/src/main/java/org/eclipse/ditto/connectivity/service/mapping/DittoMessageMapper.java
  connectivity/service/src/main/java/org/eclipse/ditto/connectivity/service/mapping/UpdateTwinWithLiveResponseMessageMapper.java
  connectivity/service/src/main/java/org/eclipse/ditto/connectivity/service/mapping/javascript/DefaultIncomingMapping.java
  gateway/service/src/main/java/org/eclipse/ditto/gateway/service/endpoints/routes/devops/DevOpsRoute.java
  gateway/service/src/main/java/org/eclipse/ditto/gateway/service/endpoints/routes/things/FeaturesRoute.java
  gateway/service/src/main/java/org/eclipse/ditto/gateway/service/endpoints/routes/things/ThingsRoute.java
  policies/model/src/main/java/org/eclipse/ditto/policies/model/signals/commands/PolicyErrorResponse.java
  protocol/src/main/java/org/eclipse/ditto/protocol/adapter/AbstractAdapter.java
  protocol/src/main/java/org/eclipse/ditto/protocol/adapter/DittoProtocolAdapter.java
  things/api/src/main/java/org/eclipse/ditto/things/api/commands/sudo/SudoRetrieveThingResponse.java
  things/api/src/main/java/org/eclipse/ditto/things/api/commands/sudo/SudoRetrieveThingsResponse.java
  things/model/src/main/java/org/eclipse/ditto/things/model/signals/commands/ThingErrorResponse.java
  things/model/src/main/java/org/eclipse/ditto/things/model/signals/commands/query/RetrieveThingsResponse.java
  thingsearch/model/src/main/java/org/eclipse/ditto/thingsearch/model/signals/commands/SearchErrorResponse.java
Labels: bug

#1798 fix that JsonObjectBuilder.remove removes to much in certain cases
  json/src/main/java/org/eclipse/ditto/json/ImmutableJsonObjectBuilder.java
  json/src/test/java/org/eclipse/ditto/json/ImmutableJsonObjectBuilderTest.java
  things/service/src/main/java/org/eclipse/ditto/things/service/persistence/serializer/ThingMongoEventAdapter.java
Labels: bug

#1791 Add piggyback commands to ui
  ui/index.html
  ui/main.ts
  ui/modules/connections/connectionsCRUD.ts
  ui/modules/connections/connectionsMonitor.ts
  ui/modules/environments/environments.ts
  ui/modules/operations/operations.html
  ui/modules/operations/piggyback.html
  ui/modules/operations/piggyback.ts
  ui/modules/operations/piggybackPlaceholders.json
  ui/modules/operations/piggybackTemplates.json
  ui/modules/operations/servicesLogging.html
  ui/modules/operations/servicesLogging.ts
  ui/modules/operations/templates.html
  ui/modules/operations/templates.ts
  ui/modules/policies/policies.ts
  ui/modules/things/featureMessages.ts
  ui/modules/things/features.ts
  ui/modules/things/messagesIncoming.ts
  ui/modules/things/thingMessages.ts
  ui/modules/things/thingsCRUD.ts
  ui/modules/things/wotDescription.ts
  ui/modules/utils.ts
Labels: UI

#1802 #1801 Add trusted certificates configuration for HonoConnection.
  connectivity/service/src/main/java/org/eclipse/ditto/connectivity/service/config/DefaultHonoConfig.java
  connectivity/service/src/main/java/org/eclipse/ditto/connectivity/service/config/HonoConfig.java
  connectivity/service/src/main/java/org/eclipse/ditto/connectivity/service/messaging/hono/DefaultHonoConnectionFactory.java
  connectivity/service/src/main/java/org/eclipse/ditto/connectivity/service/messaging/hono/HonoConnectionFactory.java
  connectivity/service/src/main/resources/connectivity.conf
  connectivity/service/src/test/java/org/eclipse/ditto/connectivity/service/config/DefaultHonoConfigTest.java
  connectivity/service/src/test/java/org/eclipse/ditto/connectivity/service/messaging/hono/DefaultHonoConnectionFactoryTest.java
  connectivity/service/src/test/java/org/eclipse/ditto/connectivity/service/messaging/persistence/ConnectionPersistenceActorTest.java
  connectivity/service/src/test/resources/hono-connection-custom-expected-after-adaptation.json
  connectivity/service/src/test/resources/hono-connection-implicit-tenant-custom-expected-after-adaptation.json
  connectivity/service/src/test/resources/test.conf
  documentation/src/main/resources/pages/ditto/connectivity-protocol-bindings-hono.md
Labels: bug

#1808 Fix set command from template to command editor
  ui/modules/operations/piggyback.ts
Labels: bug, UI

#1793 UI policy imports
  ui/index.html
  ui/main.scss
  ui/main.ts
  ui/modules/api.ts
  ui/modules/connections/connectionsMonitor.ts
  ui/modules/environments/environments.html
  ui/modules/policies/policies.html
  ui/modules/policies/policies.ts
  ui/modules/policies/policiesEntries.ts
  ui/modules/policies/policiesImports.ts
  ui/modules/policies/policiesJSON.ts
  ui/modules/policies/policiesResources.ts
  ui/modules/policies/policiesSubjects.ts
  ui/modules/policies/policyTemplates.json
  ui/modules/policies/resourceTemplates.json
  ui/modules/things/attributes.ts
  ui/modules/things/featureMessages.html
  ui/modules/things/featureMessages.ts
  ui/modules/things/features.html
  ui/modules/things/features.ts
  ui/modules/things/fields.ts
  ui/modules/things/messagesIncoming.ts
  ui/modules/things/thingMessages.html
  ui/modules/things/thingMessages.ts
  ui/modules/things/things.html
  ui/modules/things/thingsCRUD.ts
  ui/modules/things/thingsSSE.ts
  ui/modules/things/thingsSearch.ts
  ui/modules/utils.ts
  ui/modules/utils/crudToolbar.html
  ui/modules/utils/crudToolbar.ts
  ui/modules/utils/observable.ts
  ui/modules/utils/tabHandler.ts
Labels: UI

#1805 UI - Allow editors in full screen mode
  ui/main.scss
  ui/modules/connections/connections.html
  ui/modules/things/features.html
  ui/modules/things/things.html
  ui/modules/utils/crudToolbar.html
  ui/modules/utils/crudToolbar.ts
Labels: UI

#1813 enhance "Incoming Thing Updates" in UI to provide more information at a glance
  ui/modules/things/messagesIncoming.html
  ui/modules/things/messagesIncoming.ts
Labels: UI

#1812 display attributes in UI in an aceEditor instead of a simple inputfield
  ui/main.scss
  ui/modules/things/attributes.ts
  ui/modules/things/things.html
Labels: UI

#1810 fix that non-successful message responses were not displayed in ACE editor
  ui/modules/api.ts
  ui/modules/things/featureMessages.ts
  ui/modules/things/thingMessages.ts
Labels: bug, UI

#1824 preserve maxPid in journal aggregation
  internal/utils/persistence/src/main/java/org/eclipse/ditto/internal/utils/persistence/mongo/streaming/MongoReadJournal.java
Labels: bug

#1822 UI - fix for #1821 (401 on startup)
  ui/modules/operations/piggyback.ts
  ui/modules/utils/tabHandler.ts
Labels: bug, UI

#1828 #1826 fix JsonFieldSelectorTrie logic for objects and parts of those objects both being included in selected fields
  json/src/main/java/org/eclipse/ditto/json/JsonFieldSelectorTrie.java
  json/src/test/java/org/eclipse/ditto/json/JsonFieldSelectorTrieTest.java
Labels: bug

#1816 fix that a "wrong" JsonPointer in a search RQL query lead to ERRORs
  thingsearch/service/src/main/java/org/eclipse/ditto/thingsearch/service/starter/actors/SearchActor.java
Labels: bug
