Repository eclipse-ditto/ditto, pull requests merged in 2023-07, with the labels that each got.

#1676 fix(helm): Allow connectivity inter cluster communication
  deployment/helm/ditto/Chart.yaml
  deployment/helm/ditto/values.yaml
Labels: Helm chart

#1675 fix JsonSchema for policy "announcements"
  documentation/src/main/resources/jsonschema/policy.json
Labels: bug, documentation

#1680 fix MergeThing command being used for creating new things did not respect "inlinePolicy"
  edge/service/src/test/java/org/eclipse/ditto/edge/service/placeholders/ImmutableFeaturePlaceholderTest.java
  protocol/src/main/java/org/eclipse/ditto/protocol/mapper/ThingMergeSignalMapper.java
  protocol/src/test/java/org/eclipse/ditto/protocol/adapter/things/ThingMergeCommandAdapterTest.java
  things/model/src/main/java/org/eclipse/ditto/things/model/signals/commands/modify/MergeThing.java
  things/model/src/test/java/org/eclipse/ditto/things/model/signals/commands/modify/MergeThingTest.java
  things/service/src/main/java/org/eclipse/ditto/things/service/enforcement/ThingCommandEnforcement.java
  things/service/src/main/java/org/eclipse/ditto/things/service/enforcement/pre/ModifyToCreateThingTransformer.java
  things/service/src/main/java/org/eclipse/ditto/things/service/persistence/actors/strategies/commands/MergeThingStrategy.java
Labels: bug

#1678 fix non-correct WARN log about potentially failing connections status
  connectivity/service/src/main/java/org/eclipse/ditto/connectivity/service/messaging/BaseClientActor.java
Labels: bug

#1682 fix that CreationRestrictionPreEnforcer did not work
  base/model/src/main/java/org/eclipse/ditto/base/model/common/LikeHelper.java
  documentation/src/main/resources/pages/ditto/installation-operating.md
  internal/utils/config/src/main/resources/ditto-entity-creation.conf
  policies/enforcement/src/main/java/org/eclipse/ditto/policies/enforcement/config/DefaultCreationRestrictionConfig.java
  policies/enforcement/src/main/java/org/eclipse/ditto/policies/enforcement/config/DefaultEntityCreationConfig.java
  policies/enforcement/src/main/java/org/eclipse/ditto/policies/enforcement/pre/CreationRestrictionPreEnforcer.java
  policies/enforcement/src/test/resources/entity-creation/default.conf
  policies/enforcement/src/test/resources/entity-creation/restricted1.conf
Labels: bug

#1686 fix default value of 'jwtOnly' being 'true' in Helm chart
  deployment/helm/ditto/Chart.yaml
  deployment/helm/ditto/values.yaml
Labels: Helm chart

#1694 #1692 fix filtering of live message with empty resolved `extraFields`
  connectivity/service/src/test/java/org/eclipse/ditto/connectivity/service/messaging/persistence/SignalFilterWithFilterTest.java
  things/model/src/main/java/org/eclipse/ditto/things/model/signals/events/ThingEventToThingConverter.java
Labels: bug

#1688 UI - Migrate to typescript
  .github/workflows/maven.yml
  .github/workflows/ui-ci.yml
  ui/build.mjs
  ui/custom.d.ts
  ui/main.ts
  ui/modules/api.ts
  ui/modules/connections/connections.ts
  ui/modules/connections/connectionsCRUD.ts
  ui/modules/connections/connectionsMonitor.ts
  ui/modules/environments/authorization.ts
  ui/modules/environments/environments.ts
  ui/modules/operations/operations.ts
  ui/modules/policies/policies.ts
  ui/modules/things/attributes.ts
  ui/modules/things/featureMessages.ts
  ui/modules/things/features.ts
  ui/modules/things/fields.ts
  ui/modules/things/messagesIncoming.ts
  ui/modules/things/searchFilter.ts
  ui/modules/things/things.ts
  ui/modules/things/thingsCRUD.ts
  ui/modules/things/thingsSSE.ts
  ui/modules/things/thingsSearch.ts
  ui/modules/things/wotDescription.ts
  ui/modules/utils.ts
  ui/modules/utils/crudToolbar.ts
  ui/modules/utils/tabHandler.ts
  ui/package-lock.json
  ui/package.json
  ui/tsconfig.json
Labels: UI

#1697 fix that in Helm config `jwtOnly=false` will enabled pre-authentication in Ditto
  deployment/helm/ditto/Chart.yaml
  deployment/helm/ditto/templates/gateway-deployment.yaml
  deployment/helm/ditto/templates/swaggerui-deployment.yaml
Labels: bug, Helm chart

#1696 #1690 use correct HTTP status code for "if-equal": skip on equality
  connectivity/model/src/main/java/org/eclipse/ditto/connectivity/model/signals/commands/exceptions/ConnectionPreconditionFailedException.java
  connectivity/service/src/main/java/org/eclipse/ditto/connectivity/service/messaging/persistence/strategies/commands/ConnectionsConditionalHeadersValidatorProvider.java
  internal/utils/conditional-headers/src/main/java/org/eclipse/ditto/internal/utils/headers/conditional/ConditionalHeadersValidator.java
  internal/utils/conditional-headers/src/main/java/org/eclipse/ditto/internal/utils/headers/conditional/IfEqualPreconditionHeader.java
  policies/model/src/main/java/org/eclipse/ditto/policies/model/signals/commands/exceptions/PolicyPreconditionFailedException.java
  policies/service/src/main/java/org/eclipse/ditto/policies/service/persistence/actors/strategies/commands/PoliciesConditionalHeadersValidatorProvider.java
  policies/service/src/test/java/org/eclipse/ditto/policies/service/persistence/actors/strategies/commands/PoliciesConditionalHeadersValidatorTest.java
  things/model/src/main/java/org/eclipse/ditto/things/model/signals/commands/exceptions/ThingPreconditionFailedException.java
  things/service/src/main/java/org/eclipse/ditto/things/service/persistence/actors/strategies/commands/ThingsConditionalHeadersValidatorProvider.java
  things/service/src/test/java/org/eclipse/ditto/things/service/persistence/actors/strategies/commands/ThingsConditionalHeadersValidatorTest.java
Labels: bug

#1695 #1691 fixed persisting inline "_policy" in ThingMerged events
  internal/utils/persistent-actors/src/main/java/org/eclipse/ditto/internal/utils/persistentactors/condition/package-info.java
  things/model/src/main/java/org/eclipse/ditto/things/model/signals/events/ThingMerged.java
  things/service/src/main/java/org/eclipse/ditto/things/service/persistence/serializer/ThingMongoEventAdapter.java
Labels: bug

#1702 Support for basic nginx-ingress authentication
  deployment/helm/ditto/Chart.yaml
  deployment/helm/ditto/templates/nginx-ingress-api.yaml
  deployment/helm/ditto/templates/nginx-ingress-auth.yaml
  deployment/helm/ditto/templates/nginx-ingress.yaml
  deployment/helm/ditto/values.yaml
Labels: Helm chart
