Repository eclipse-ditto/ditto, pull requests merged in 2024-10, with the labels that each got.

#2032 #1591 add SSO via OIDC to Ditto UI
  gateway/service/src/main/java/org/eclipse/ditto/gateway/service/security/authentication/jwt/DefaultJwtValidator.java
  gateway/service/src/main/resources/gateway-dev.conf
  ui/main.scss
  ui/main.ts
  ui/modules/api.ts
  ui/modules/environments/authorization.html
  ui/modules/environments/authorization.ts
  ui/modules/environments/environmentTemplates.json
  ui/modules/environments/environments.ts
  ui/modules/policies/policies.ts
  ui/modules/policies/policiesImports.ts
  ui/modules/policies/policiesJSON.ts
  ui/modules/things/attributes.ts
  ui/modules/things/featureMessages.ts
  ui/modules/things/features.ts
  ui/modules/things/fields.ts
  ui/modules/things/searchFilter.ts
  ui/modules/things/thingMessages.ts
  ui/modules/things/things.ts
  ui/modules/things/thingsSSE.ts
  ui/modules/things/thingsSearch.ts
  ui/modules/utils.ts
  ui/package-lock.json
  ui/package.json
  ui/readme.md
  ui/sso-test/app/login.html
  ui/sso-test/docker-compose.yml
Labels: UI

#2041 UI - bugfix for create new environment
  ui/modules/environments/environments.ts
Labels: bug, UI

#2043 fixed JS mapping header serialization to string for array headers
  connectivity/service/src/main/java/org/eclipse/ditto/connectivity/service/mapping/javascript/ScriptedOutgoingMapping.java
  connectivity/service/src/test/java/org/eclipse/ditto/connectivity/service/mapping/javascript/JavaScriptMessageMapperRhinoTest.java
Labels: bug

#2045 fix WoT tm validation "dynamic" config Helm template
  deployment/helm/ditto/Chart.yaml
  deployment/helm/ditto/templates/things-deployment.yaml
  wot/api/src/main/java/org/eclipse/ditto/wot/api/config/InternalDynamicTmValidationConfiguration.java
Labels: bug

#2048 fix enter button submitting wrong button in login dialog
  ui/modules/api.ts
  ui/modules/environments/authorization.html
Labels: bug, UI

#2050 fix that only aggregated metrics for filters which actually matched >0 things are reported
  thingsearch/model/src/main/java/org/eclipse/ditto/thingsearch/model/signals/commands/exceptions/MultipleAggregationFilterMatchingException.java
  thingsearch/model/src/main/java/org/eclipse/ditto/thingsearch/model/signals/commands/query/AggregateThingsMetricsResponse.java
  thingsearch/service/src/main/java/org/eclipse/ditto/thingsearch/service/starter/actors/AggregateThingsMetricsActor.java
  thingsearch/service/src/main/java/org/eclipse/ditto/thingsearch/service/starter/actors/OperatorAggregateMetricsProviderActor.java
Labels: bug
