Repository eclipse-ditto/ditto, pull requests merged in 2024-02, with the labels that each got.

#1889 fix wrongly done invalidation of non-existing cached policy entry in search
  thingsearch/service/src/main/java/org/eclipse/ditto/thingsearch/service/persistence/write/streaming/EnforcementFlow.java
Labels: bug

#1890 #1888 fix retrieving simple arrays via field selectors
  json/src/main/java/org/eclipse/ditto/json/ImmutableJsonObject.java
  json/src/test/java/org/eclipse/ditto/json/ImmutableJsonObjectTest.java
Labels: bug

#1891 UI small fixes and improvements
  ui/modules/api.ts
  ui/modules/connections/connections.html
  ui/modules/connections/connectionsCRUD.ts
  ui/modules/connections/connectionsMonitor.ts
  ui/modules/things/messagesIncoming.ts
Labels: bug, UI

#1897 Update deployment files and unit tests to use MongoDB 6.0
  deployment/docker/docker-compose.yml
  deployment/docker/sandbox/docker-compose.yml
  deployment/helm/ditto/Chart.yaml
  deployment/helm/ditto/README.md
  deployment/kubernetes/deploymentFiles/mongodb-statefulset/mongodb-statefulset.yaml
  deployment/kubernetes/deploymentFiles/mongodb/mongodb.yaml
  documentation/src/main/resources/pages/ditto/installation-running.md
  internal/utils/test/src/test/java/org/eclipse/ditto/internal/utils/test/docker/mongo/MongoContainerFactory.java
  thingsearch/service/src/test/java/org/eclipse/ditto/thingsearch/service/persistence/write/mapping/BsonDiffVisitorV5IT.java
Labels: Helm chart

#1902 Added option to add custom annotations to podDeletionCostPatching jobs.
  deployment/helm/ditto/Chart.yaml
  deployment/helm/ditto/templates/hooks/pod-deletion-cost-cron-job.yaml
  deployment/helm/ditto/templates/hooks/pre-upgrade-job.yaml
  deployment/helm/ditto/values.yaml
Labels: Helm chart

#1901 fix that "Incoming Thing Updates" always repeated the first entry
  ui/modules/things/messagesIncoming.ts
Labels: bug, UI

#1904 #1893 fix ensuring the consistency when doing signal enrichment
  internal/models/signalenrichment/src/main/java/org/eclipse/ditto/internal/models/signalenrichment/CachingSignalEnrichmentFacade.java
  internal/models/signalenrichment/src/main/java/org/eclipse/ditto/internal/models/signalenrichment/DittoCachingSignalEnrichmentFacade.java
  internal/models/signalenrichment/src/main/java/org/eclipse/ditto/internal/models/signalenrichment/SignalEnrichmentCacheKey.java
  internal/models/signalenrichment/src/main/java/org/eclipse/ditto/internal/models/signalenrichment/SignalEnrichmentCacheLoader.java
  internal/models/signalenrichment/src/main/java/org/eclipse/ditto/internal/models/signalenrichment/SignalEnrichmentContext.java
  internal/utils/persistent-actors/src/main/java/org/eclipse/ditto/internal/utils/persistentactors/AbstractPersistenceActor.java
Labels: bug

#1903 fix time:now placeholder truncation
  base/model/src/main/java/org/eclipse/ditto/base/model/signals/GlobalErrorRegistry.java
  placeholders/src/main/java/org/eclipse/ditto/placeholders/ImmutableTimePlaceholder.java
Labels: bug
