Repository eclipse-ditto/ditto, pull requests merged in 2024-06, with the labels that each got.

#1953 bugfix/ws-ingress-auth-fix
  deployment/helm/ditto/Chart.yaml
  deployment/helm/ditto/templates/nginx-ingress-ws.yaml
Labels: Helm chart

#1954 Add possibility to customize image used for pod-deletion-cost annotation patching job
  deployment/helm/ditto/Chart.yaml
  deployment/helm/ditto/templates/hooks/pod-deletion-cost-cron-job.yaml
  deployment/helm/ditto/templates/hooks/pre-upgrade-job.yaml
  deployment/helm/ditto/values.yaml
Labels: Helm chart

#1948 #1946 fix that alternative OIDC provider for "devops" authorization could not be configured
  deployment/helm/ditto/Chart.yaml
  deployment/helm/ditto/templates/gateway-deployment.yaml
  gateway/service/src/main/java/org/eclipse/ditto/gateway/service/endpoints/actors/AbstractConnectionsRetrievalActor.java
  gateway/service/src/main/java/org/eclipse/ditto/gateway/service/endpoints/directives/auth/DevOpsBasicAuthenticationDirective.java
  gateway/service/src/main/java/org/eclipse/ditto/gateway/service/endpoints/directives/auth/DevOpsInsecureAuthenticationDirective.java
  gateway/service/src/main/java/org/eclipse/ditto/gateway/service/endpoints/directives/auth/DevOpsOAuth2AuthenticationDirective.java
  gateway/service/src/main/java/org/eclipse/ditto/gateway/service/endpoints/directives/auth/DevopsAuthenticationDirective.java
  gateway/service/src/main/java/org/eclipse/ditto/gateway/service/endpoints/directives/auth/DevopsAuthenticationDirectiveFactory.java
  gateway/service/src/main/java/org/eclipse/ditto/gateway/service/endpoints/directives/auth/DittoGatewayAuthenticationDirectiveFactory.java
  gateway/service/src/main/java/org/eclipse/ditto/gateway/service/endpoints/routes/RootRoute.java
  gateway/service/src/main/java/org/eclipse/ditto/gateway/service/endpoints/routes/connections/ConnectionsRoute.java
  gateway/service/src/main/java/org/eclipse/ditto/gateway/service/endpoints/routes/devops/DevOpsRoute.java
  gateway/service/src/main/java/org/eclipse/ditto/gateway/service/endpoints/routes/stats/StatsRoute.java
  gateway/service/src/main/java/org/eclipse/ditto/gateway/service/endpoints/routes/status/OverallStatusRoute.java
  gateway/service/src/main/java/org/eclipse/ditto/gateway/service/security/authentication/jwt/DittoJwtAuthorizationSubjectsProvider.java
  gateway/service/src/main/java/org/eclipse/ditto/gateway/service/security/authentication/jwt/JwtAuthenticationFactory.java
  gateway/service/src/main/java/org/eclipse/ditto/gateway/service/security/authentication/jwt/JwtAuthenticationProvider.java
  gateway/service/src/main/java/org/eclipse/ditto/gateway/service/security/authentication/jwt/JwtAuthenticationResultProvider.java
  gateway/service/src/main/java/org/eclipse/ditto/gateway/service/starter/GatewayRootActor.java
  gateway/service/src/main/resources/gateway.conf
  gateway/service/src/test/java/org/eclipse/ditto/gateway/service/endpoints/EndpointTestBase.java
  gateway/service/src/test/java/org/eclipse/ditto/gateway/service/endpoints/routes/RootRouteTest.java
  gateway/service/src/test/java/org/eclipse/ditto/gateway/service/endpoints/routes/connections/ConnectionsRouteTest.java
  gateway/service/src/test/java/org/eclipse/ditto/gateway/service/endpoints/routes/devops/DevOpsRouteTest.java
  gateway/service/src/test/java/org/eclipse/ditto/gateway/service/endpoints/routes/stats/StatsRouteTest.java
  gateway/service/src/test/java/org/eclipse/ditto/gateway/service/endpoints/routes/status/OverallStatusRouteTest.java
  gateway/service/src/test/java/org/eclipse/ditto/gateway/service/security/authentication/jwt/DefaultJwtAuthenticationResultProviderTest.java
  gateway/service/src/test/resources/test.conf
Labels: bug

#1956 Fix performance regression issue when running against MongoDB 6
  connectivity/service/src/main/resources/connectivity.conf
  internal/utils/persistence/src/main/java/org/eclipse/ditto/internal/utils/persistence/mongo/AbstractPersistenceStreamingActor.java
  internal/utils/persistence/src/main/java/org/eclipse/ditto/internal/utils/persistence/mongo/SnapshotStreamingActor.java
  internal/utils/persistence/src/main/java/org/eclipse/ditto/internal/utils/persistence/mongo/config/DefaultMongoDbConfig.java
  internal/utils/persistence/src/main/java/org/eclipse/ditto/internal/utils/persistence/mongo/config/DefaultMongoReadJournalConfig.java
  internal/utils/persistence/src/main/java/org/eclipse/ditto/internal/utils/persistence/mongo/config/MongoDbConfig.java
  internal/utils/persistence/src/main/java/org/eclipse/ditto/internal/utils/persistence/mongo/config/MongoReadJournalConfig.java
  internal/utils/persistence/src/main/java/org/eclipse/ditto/internal/utils/persistence/mongo/indices/IndexOperations.java
  internal/utils/persistence/src/main/java/org/eclipse/ditto/internal/utils/persistence/mongo/streaming/MongoReadJournal.java
  internal/utils/persistence/src/test/java/org/eclipse/ditto/internal/utils/persistence/mongo/config/DefaultMongoDbConfigTest.java
  internal/utils/persistence/src/test/java/org/eclipse/ditto/internal/utils/persistence/mongo/streaming/MongoReadJournalIT.java
  policies/service/src/main/resources/policies.conf
  things/service/src/main/java/org/eclipse/ditto/things/service/starter/ThingsRootActor.java
  things/service/src/main/resources/things.conf
Labels: bug

#1962 #1959: fix `base` and `href` of generated WoT ThingDescriptions
  wot/integration/src/main/java/org/eclipse/ditto/wot/integration/generator/DefaultWotThingDescriptionGenerator.java
Labels: bug

#1961 enable configuring even more flexibly indexes to `hint` for in Cleanup aggregations
  connectivity/service/src/main/resources/connectivity.conf
  internal/utils/persistence/src/main/java/org/eclipse/ditto/internal/utils/persistence/mongo/config/DefaultMongoReadJournalConfig.java
  internal/utils/persistence/src/main/java/org/eclipse/ditto/internal/utils/persistence/mongo/config/MongoReadJournalConfig.java
  internal/utils/persistence/src/main/java/org/eclipse/ditto/internal/utils/persistence/mongo/streaming/MongoReadJournal.java
  internal/utils/persistent-actors/src/main/java/org/eclipse/ditto/internal/utils/persistentactors/cleanup/Cleanup.java
  internal/utils/persistent-actors/src/main/java/org/eclipse/ditto/internal/utils/persistentactors/cleanup/PersistenceCleanupActor.java
  internal/utils/persistent-actors/src/test/java/org/eclipse/ditto/internal/utils/persistentactors/cleanup/CleanupTest.java
  internal/utils/persistent-actors/src/test/java/org/eclipse/ditto/internal/utils/persistentactors/cleanup/CreditsTest.java
  internal/utils/persistent-actors/src/test/java/org/eclipse/ditto/internal/utils/persistentactors/cleanup/PersistenceCleanupActorTest.java
  policies/service/src/main/resources/policies.conf
  things/service/src/main/resources/things.conf
Labels: bug

#1963 make logstash buffer sizes configurable
  connectivity/service/src/main/resources/logback.xml
  deployment/helm/ditto/Chart.yaml
  deployment/helm/ditto/templates/connectivity-deployment.yaml
  deployment/helm/ditto/templates/gateway-deployment.yaml
  deployment/helm/ditto/templates/policies-deployment.yaml
  deployment/helm/ditto/templates/things-deployment.yaml
  deployment/helm/ditto/templates/thingssearch-deployment.yaml
  deployment/helm/ditto/values.yaml
  gateway/service/src/main/resources/logback.xml
  policies/service/src/main/resources/logback.xml
  things/service/src/main/resources/logback.xml
  thingsearch/service/src/main/resources/logback.xml
Labels: Helm chart

#1964 fix performance regression with MongoDB 6 regarding snapshot aggregations
  connectivity/service/src/main/resources/connectivity.conf
  deployment/helm/ditto/Chart.yaml
  deployment/helm/ditto/templates/connectivity-deployment.yaml
  deployment/helm/ditto/templates/policies-deployment.yaml
  deployment/helm/ditto/templates/things-deployment.yaml
  deployment/helm/ditto/values.yaml
  documentation/src/main/resources/pages/ditto/installation-operating.md
  internal/utils/persistence/src/main/java/org/eclipse/ditto/internal/utils/persistence/mongo/config/DefaultMongoReadJournalConfig.java
  internal/utils/persistence/src/main/java/org/eclipse/ditto/internal/utils/persistence/mongo/config/MongoReadJournalConfig.java
  internal/utils/persistence/src/main/java/org/eclipse/ditto/internal/utils/persistence/mongo/streaming/MongoReadJournal.java
  internal/utils/persistent-actors/src/main/java/org/eclipse/ditto/internal/utils/persistentactors/cleanup/Cleanup.java
  policies/service/src/main/resources/policies.conf
  things/service/src/main/resources/things.conf
Labels: bug, Helm chart

#1971 fix MongoReadJournalIT
  internal/utils/persistence/src/test/resources/mongo-read-journal-test.conf
Labels: bug
