Repository eclipse-ditto/ditto, pull requests merged in 2024-09, with the labels that each got.

#2013 Helm: create empty dir for heapdumps and more
  deployment/helm/ditto/Chart.yaml
  deployment/helm/ditto/templates/connectivity-deployment.yaml
  deployment/helm/ditto/templates/gateway-deployment.yaml
  deployment/helm/ditto/templates/policies-deployment.yaml
  deployment/helm/ditto/templates/things-deployment.yaml
  deployment/helm/ditto/templates/thingssearch-deployment.yaml
  deployment/helm/ditto/values.yaml
Labels: Helm chart

#2014 monitoring connection pool config key fix
  thingsearch/service/src/main/resources/search.conf
  thingsearch/service/src/test/resources/actors-test.conf
Labels: bug

#2017 fix search background sync being stuck
  deployment/docker/docker-compose.yml
  deployment/docker/sandbox/docker-compose.yml
  deployment/kubernetes/deploymentFiles/mongodb-statefulset/mongodb-statefulset.yaml
  deployment/kubernetes/deploymentFiles/mongodb/mongodb.yaml
  internal/utils/persistence/src/main/java/org/eclipse/ditto/internal/utils/persistence/mongo/streaming/MongoTimestampPersistence.java
Labels: bug

#2025 #2022 provide the option to log a warning instead of failing modifying API calls in WoT based validation
  deployment/helm/ditto/Chart.yaml
  deployment/helm/ditto/templates/things-deployment.yaml
  deployment/helm/ditto/values.yaml
  things/service/src/main/resources/things.conf
  wot/api/src/main/java/org/eclipse/ditto/wot/api/config/DefaultTmValidationConfig.java
  wot/api/src/main/java/org/eclipse/ditto/wot/api/validator/DefaultWotThingModelValidator.java
  wot/validation/src/main/java/org/eclipse/ditto/wot/validation/config/TmValidationConfig.java
Labels: WoT

#2033 #1915 fix retrieving the historical value of a thing with `at-historical-timestamp`
  internal/utils/persistent-actors/src/main/java/org/eclipse/ditto/internal/utils/persistentactors/AbstractPersistenceActor.java
Labels: bug

#2026 #1951 generate EPOCH timestamp as neutral element for string "format" date-time, date, time
  wot/api/src/main/java/org/eclipse/ditto/wot/api/generator/DefaultWotThingSkeletonGenerator.java
Labels: bug
