Repository eclipse-ditto/ditto, pull requests merged in 2024-01, with the labels that each got.

#1848 fixed that "condition" query param could not be provided as form field
  documentation/src/main/resources/openapi/ditto-api-2.yml
  documentation/src/main/resources/openapi/sources/paths/search/things.yml
  documentation/src/main/resources/openapi/sources/schemas/properties/searchConditionProperty.yml
  edge/service/src/main/java/org/eclipse/ditto/edge/service/headers/DefaultDittoHeadersValidator.java
  gateway/service/src/main/java/org/eclipse/ditto/gateway/service/endpoints/routes/RootRouteHeadersStepBuilder.java
  gateway/service/src/main/java/org/eclipse/ditto/gateway/service/endpoints/routes/thingsearch/ThingSearchRoute.java
  gateway/service/src/test/java/org/eclipse/ditto/gateway/service/endpoints/routes/thingsearch/ThingSearchRouteTest.java
Labels: bug

#1863 Fix enrichment of ThingCreated events with _policy
  internal/models/signalenrichment/src/main/java/org/eclipse/ditto/internal/models/signalenrichment/DittoCachingSignalEnrichmentFacade.java
  thingsearch/service/src/test/java/org/eclipse/ditto/thingsearch/service/persistence/write/streaming/EnforcementFlowTest.java
Labels: bug

#1864 Enhance things search slot by displaying the amount of matching things
  ui/modules/things/things.html
  ui/modules/things/thingsSearch.ts
Labels: UI

#1872 #1869 use cache in order to load imported policies when policies are …
  internal/utils/cache/src/main/java/org/eclipse/ditto/internal/utils/cache/Cache.java
  internal/utils/cache/src/main/java/org/eclipse/ditto/internal/utils/cache/CaffeineCache.java
  internal/utils/cache/src/main/java/org/eclipse/ditto/internal/utils/cache/ProjectedCache.java
  policies/enforcement/src/main/java/org/eclipse/ditto/policies/enforcement/PolicyEnforcerCache.java
  policies/model/src/main/java/org/eclipse/ditto/policies/model/PolicyImport.java
  thingsearch/service/src/main/java/org/eclipse/ditto/thingsearch/service/persistence/read/MongoThingsSearchPersistence.java
  thingsearch/service/src/main/java/org/eclipse/ditto/thingsearch/service/persistence/write/mapping/EnforcedThingMapper.java
  thingsearch/service/src/main/java/org/eclipse/ditto/thingsearch/service/persistence/write/model/Metadata.java
  thingsearch/service/src/main/java/org/eclipse/ditto/thingsearch/service/persistence/write/model/ThingWriteModel.java
  thingsearch/service/src/main/java/org/eclipse/ditto/thingsearch/service/persistence/write/streaming/BackgroundSyncStream.java
  thingsearch/service/src/main/java/org/eclipse/ditto/thingsearch/service/persistence/write/streaming/EnforcementFlow.java
  thingsearch/service/src/main/java/org/eclipse/ditto/thingsearch/service/persistence/write/streaming/ResolvedPolicyCacheLoader.java
  thingsearch/service/src/main/java/org/eclipse/ditto/thingsearch/service/persistence/write/streaming/SearchUpdateMapper.java
  thingsearch/service/src/main/java/org/eclipse/ditto/thingsearch/service/updater/actors/ThingUpdater.java
  thingsearch/service/src/main/java/org/eclipse/ditto/thingsearch/service/updater/actors/ThingsMetadataSource.java
  thingsearch/service/src/test/java/org/eclipse/ditto/thingsearch/service/persistence/read/SudoIT.java
  thingsearch/service/src/test/java/org/eclipse/ditto/thingsearch/service/persistence/write/mapping/BsonDiffVisitorIT.java
  thingsearch/service/src/test/java/org/eclipse/ditto/thingsearch/service/persistence/write/model/MetadataTest.java
  thingsearch/service/src/test/java/org/eclipse/ditto/thingsearch/service/persistence/write/model/ThingWriteModelIT.java
  thingsearch/service/src/test/java/org/eclipse/ditto/thingsearch/service/persistence/write/streaming/BackgroundSyncStreamTest.java
  thingsearch/service/src/test/java/org/eclipse/ditto/thingsearch/service/persistence/write/streaming/BulkWriteResultAckFlowTest.java
  thingsearch/service/src/test/java/org/eclipse/ditto/thingsearch/service/persistence/write/streaming/EnforcementFlowTest.java
  thingsearch/service/src/test/java/org/eclipse/ditto/thingsearch/service/persistence/write/streaming/TestSearchUpdaterStream.java
  thingsearch/service/src/test/java/org/eclipse/ditto/thingsearch/service/updater/actors/BackgroundSyncActorTest.java
  thingsearch/service/src/test/java/org/eclipse/ditto/thingsearch/service/updater/actors/ThingUpdaterTest.java
Labels: bug

#1875 Fix helm chart open shift identation
  deployment/helm/ditto/Chart.yaml
  deployment/helm/ditto/templates/connectivity-deployment.yaml
  deployment/helm/ditto/templates/gateway-deployment.yaml
  deployment/helm/ditto/templates/policies-deployment.yaml
  deployment/helm/ditto/templates/things-deployment.yaml
  deployment/helm/ditto/templates/thingssearch-deployment.yaml
Labels: Helm chart

#1862 UI - Add filter for tables
  ui/__tests__/utils/basicFilter.test.ts
  ui/jest.config.ts
  ui/main.ts
  ui/modules/connections/connections.html
  ui/modules/connections/connectionsMonitor.ts
  ui/modules/policies/policies.html
  ui/modules/things/featureMessages.ts
  ui/modules/things/messagesIncoming.html
  ui/modules/things/messagesIncoming.ts
  ui/modules/things/searchFilter.ts
  ui/modules/things/thingMessages.ts
  ui/modules/things/things.html
  ui/modules/utils.ts
  ui/modules/utils/basicFilters.ts
  ui/modules/utils/tableFilter.html
  ui/modules/utils/tableFilter.ts
  ui/package-lock.json
  ui/package.json
  ui/readme.md
  ui/tsconfig.json
Labels: UI

#1883 #1882 fixed ResolvedPolicyCacheLoader loading policy imports transitively
  thingsearch/service/src/main/java/org/eclipse/ditto/thingsearch/service/persistence/write/streaming/EnforcementFlow.java
  thingsearch/service/src/main/java/org/eclipse/ditto/thingsearch/service/persistence/write/streaming/PolicyIdResolvingImports.java
  thingsearch/service/src/main/java/org/eclipse/ditto/thingsearch/service/persistence/write/streaming/ResolvedPolicyCacheLoader.java
  thingsearch/service/src/test/java/org/eclipse/ditto/thingsearch/service/persistence/write/streaming/EnforcementFlowTest.java
Labels: bug

#1884 fix Helm config for operatorMetrics not having defined a "scrapeInterval"
  deployment/helm/ditto/Chart.yaml
  deployment/helm/ditto/templates/thingssearch-deployment.yaml
Labels: bug, Helm chart

#1886 Helm: fix hook scripts uses release name instead of fullname
  deployment/helm/ditto/Chart.yaml
  deployment/helm/ditto/templates/hooks/scripts-configmap.yaml
Labels: Helm chart
