Repository eclipse-ditto/ditto, pull requests merged in 2025-03, with the labels that each got.

#2134 fix configuration of throttling of search index update after policy update
  base/service/src/main/java/org/eclipse/ditto/base/service/config/ThrottlingConfig.java
  deployment/helm/ditto/Chart.yaml
  deployment/helm/ditto/templates/thingssearch-deployment.yaml
  deployment/helm/ditto/values.yaml
  thingsearch/service/src/main/java/org/eclipse/ditto/thingsearch/service/persistence/write/impl/MongoThingsSearchUpdaterPersistence.java
  thingsearch/service/src/main/resources/search.conf
Labels: bug, Helm chart

#2136 fix MigrateThingDefinition wot validation issue
  internal/utils/persistent-actors/src/main/java/org/eclipse/ditto/internal/utils/persistentactors/AbstractPersistenceActor.java
  things/service/src/main/java/org/eclipse/ditto/things/service/persistence/actors/ThingPersistenceActor.java
Labels: bug

#2140 fix kamon.conf to be loaded in config
  connectivity/service/src/main/resources/connectivity.conf
  gateway/service/src/main/resources/gateway.conf
  internal/utils/config/src/main/resources/ditto-kamon.conf
  policies/service/src/main/resources/policies.conf
  things/service/src/main/resources/things.conf
  thingsearch/service/src/main/resources/search.conf
Labels: bug

#2137 fix pre-defined extraFields were causing missing extra from Thing created events
  internal/models/signalenrichment/src/main/java/org/eclipse/ditto/internal/models/signalenrichment/DittoCachingSignalEnrichmentFacade.java
  things/service/src/main/java/org/eclipse/ditto/things/service/persistence/actors/ThingPersistenceActor.java
Labels: bug

#2139 fix http-push-connection-dispatcher config overrides
  connectivity/service/src/main/resources/connectivity.conf
Labels: bug

#2149 fix SSO in Ditto UI not presenting login page when session is expired
  ui/modules/environments/authorization.ts
Labels: bug, UI

#2152 #2148: fix primitive values validation issue
  wot/validation/src/main/java/org/eclipse/ditto/wot/validation/JsonSchemaTools.java
  wot/validation/src/test/java/org/eclipse/ditto/wot/validation/WotThingModelValidationFeatureLevelTest.java
Labels: bug
